language: node_js
node_js:
  - 8
  - 10

env:
  global:
  - SAUCE_USERNAME: vojtajina
  - secure: "k2x1puIrj42LqnWF8SoDod19xpeJhJN3RDMgRLK2LTYffcdJV8TXilPRUk4pXyN6u8B79fxAW8WucsrlxB6CaaB5cXsFTDG+jpO21AlFc3mFjPh6sTkp/1L/bxc3cJNc9w18Ol2+8MO5s37xuy/lJaQeBRFxQleZZWCLLjtXytg="

# Make sure we have new NPM.
before_install:
  - if [[ "`node --version`" = v4* ]]; then npm install -g npm@latest-3; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./run.sh karma@latest
